version: "3.9"
services:
  pedidapp-service:
    build: .
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pedidapp
      MYSQL_USER: csom
      MYSQL_PASSWORD: 20081987
    ports:
      - "3306:3306"
    networks:
      - spring-network
    volumes:
      - mysql-db-data:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-db-data: